name: pymarchenko
channels:
  - defaults
  - conda-forge
  - numba
dependencies:
  - python>=3.6.4
  - pip
  - numpy>=1.15.0
  - scipy>=1.1.0
  - pylops>=2.0
  - matplotlib
  - ipython
  - pytest
  - sphinx
  - numpydoc
  - numba
  - icc_rt
  - pip:
    - pytest-runner
    - setuptools_scm
    - pydata-sphinx-theme
    - sphinx-gallery
    - sphinxemoji
    - nbsphinx
    - image